[build]
  command = "npm run build"
  publish = "dist"

# Убедись, что .js файлы раздаются с правильным Content-Type
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"